### ISSUE TITLE
Sourcing Content

### ISSUE THREAD

**Issue by tvOSPopcorn** [timroesner/tvOS-movies#1]
Hi,

I'm curious of your application, how do you plan on fetching content, meta data etc? I noticed you're setup to fetch content from a json file on a web server are you planning on doing everything manually or have plans to scrape content from sites like 123movies for an example and create you're own API?

**Comment by timroesner** [comment]
I'm creating my own API, but it is currently not working due to unresolved issues. Also I am still working on reverse engineering the redirector links as they currently expire after an hour or so.

**Comment by timroesner** [comment]
Hey there,

Update on the progress, I now use OneDrive to host the files myself and still have an API with a SQL database in the back end. Also cleaned it up a little, if you want to give it a try it's completely functional now.

**Comment by timroesner** [comment]
Hi,

So I did look into scrapping a lot but their links do expire quite frequently why it's not usable. I am up to about 50 movies now, search is also working. If you have requests for movies post them here, or if you already have it uploaded to a server hand me the link and I'll add it.
