### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sqig** [timroesner/tvOS-movies#4]
Hello,
When i try to build you app I get this error.

Compress PNG Files Error Group
ERROR: Can't find /Users/jason/Desktop/10.2 Videos Fix - iPhone/10.2 Videos Fix - iPhone/MissingArtworkMovies.png
Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng failed with exit code 1

What am I doing wrong ?

Xcode 9.2

Thank you.

**Comment by timroesner** [comment]
Hi @sqig 
Thank you for letting me know about this. You weren't doing anything wrong it was just a missing placeholder image which is fixed in the latest commit.
Let me know if you have any other questions.
